- name: os update
  yum: name=* state=latest

- name: download  zabbix-agent 4.0 repo
  yum:
    name: http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-agent-4.0.14-1.el7.x86_64.rpm
    state: present

- name: install zabbix-agent
  yum:
    name: zabbix-agent
    state: present

- name: copy zabbix_agentd.conf
  copy:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf

- name: start zabbix-agent
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
