- name: copy config files of zabbix
  copy: src="{{ item.src}}" dest="{{ item.dest }}" mode="{{ item.mode }}"
  with_items:
      - { src: 'zabbix_server.conf', dest: '/etc/zabbix/zabbix_server.conf', mode: '0640' }
      - { src: 'zabbix.conf', dest: '/etc/httpd/conf.d/zabbix.conf', mode: '0644' }
      - { src: 'php.ini', dest: '/etc/php.ini', mode: '0644' }
